/**
 * Global i18n module for eruda.
 *
 * - Default language follows the system (navigator.language).
 * - Manual switch between English ("en") and Chinese ("zh"),
 *   persisted to localStorage and shared by every tool.
 * - Dictionary keys are either the English source strings themselves
 *   (e.g. t('Theme')) or legacy camelCase keys used by the Network tool.
 * - Missing keys fall back to English, then to the key itself, so it is
 *   safe to wrap any string with t().
 */
import emitter from './emitter'

const LANG_KEY = 'eruda-lang'
const LEGACY_LANG_KEY = 'eruda_np_lang'

const en = {
  // ---- Network tool (legacy camelCase keys, kept for compatibility) ----
  record: 'Record',
  stop: 'Stop recording',
  clear: 'Clear',
  exportHar: 'Export HAR',
  importHar: 'Import HAR',
  rules: 'Block / Rewrite / Mock',
  throttle: 'Throttling',
  lang: '中文',
  searchPh: 'Filter  (/regex/  -exclude)',
  all: 'All',
  xhr: 'Fetch/XHR',
  js: 'JS',
  css: 'CSS',
  img: 'Img',
  media: 'Media',
  font: 'Font',
  doc: 'Doc',
  other: 'Other',
  requests: 'requests',
  transferred: 'transferred',
  finish: 'Finish',
  failed: 'failed',
  headers: 'Headers',
  cookies: 'Cookies',
  payload: 'Payload',
  preview: 'Preview',
  response: 'Response',
  initiator: 'Initiator',
  timing: 'Timing',
  stalled: 'Stalled',
  general: 'General',
  requestUrl: 'Request URL',
  originalUrl: 'Original URL (before rewrite)',
  requestMethod: 'Request Method',
  statusCode: 'Status Code',
  responseHeaders: 'Response Headers',
  requestHeaders: 'Request Headers',
  queryParams: 'Query String Parameters',
  formData: 'Form Data',
  requestPayload: 'Request Payload',
  replay: 'Replay',
  copyCurl: 'Copy as cURL',
  copyFetch: 'Copy as fetch',
  copyResponse: 'Copy response',
  blockedHint:
    'This request was blocked by the blocklist. It never reached the server and received a simulated HTTP 403.',
  mockHint: 'This response was generated by a Mock rule. The server was never contacted.',
  emptyBody: 'This request has no body.',
  emptyRes: '(empty response)',
  previewUnavailable: 'Preview not available for this content type.',
  timingHint:
    'Detailed phases unavailable for this request (cross-origin without Timing-Allow-Origin), total time shown.',
  noStack: 'No initiator information was captured for this request.',
  initiatorHint: 'First script frame outside the capture hook:',
  blocked: 'Block',
  rewrite: 'Rewrite',
  mock: 'Mock',
  manifestChip: 'Manifest',
  wsChip: 'WS',
  wasmChip: 'Wasm',
  socketChip: 'Socket',
  manifest: 'Manifest',
  ws: 'WS',
  wasm: 'Wasm',
  enableBlocking: 'Enable blocking',
  blockHint:
    'Literal substring or /regex/ per line, lines starting with # are ignored. Blocked requests never reach the server and get a simulated HTTP 403.',
  save: 'Save',
  enable: 'Enable',
  addRule: 'Add rule',
  rewriteHint:
    'Before a request is sent, every enabled rule rewrites its URL: /regex/ or literal substring is replaced with the replacement. Rules apply top-down.',
  mockHint2:
    'Matched requests never touch the network; a synthetic response is generated instead. Pattern: literal or /regex/.',
  status: 'Status',
  contentType: 'Content-Type',
  blockedStatus: 'blocked',
  blockedSaved: 'Blocklist saved',
  rulesApplied: 'Rules applied',
  copied: 'Copied',
  replayed: 'Replayed',
  replayFailed: 'Replay failed: ',
  harExported: 'HAR exported',
  harImported: 'HAR imported',
  harImportFailed: 'Invalid HAR file',
  throttleOff: 'No throttling',
  offline: 'Offline',

  // ---- Tool names (nav bar & settings section titles) ----
  Console: 'Console',
  Elements: 'Elements',
  Network: 'Network',
  Resources: 'Resources',
  Sources: 'Sources',
  Info: 'Info',
  Snippets: 'Snippets',
  Settings: 'Settings',

  // ---- Network detail extras ----
  provisionalHeaders: 'Provisional headers are shown.',
  learnMore: 'Learn more',
  noResponseData: 'Failed to load response data',
  currentlyRecording: 'Currently recording network activity',
  recordingHint: 'Perform a request or reload the page to see it here.',
  reloadPage: 'Reload page',
  duration: 'DURATION',
  explanation: 'Explanation',
  resourceScheduling: 'Resource Scheduling',
  connectionStart: 'Connection Start',
  requestResponse: 'Request/Response',
  queuedAt: 'Queued at',
  startedAt: 'Started at',
  totalDuration: 'Total duration',
  serverTiming: 'Server Timing',
  waitingServer: 'Waiting for server response',

  // ---- DevTools / Settings ----
  Theme: 'Theme',
  'System preference': 'System preference',
  Dark: 'Dark',
  Light: 'Light',
  Transparency: 'Transparency',
  'Display Size': 'Display Size',
  'Restore defaults and reload': 'Restore defaults and reload',
  'Language / 语言': 'Language / 语言',
  'Follow System': 'Follow system',

  // ---- Console ----
  All: 'All',
  Warning: 'Warning',
  Error: 'Error',
  Verbose: 'Verbose',
  'Default levels': 'Default levels',
  Cancel: 'Cancel',
  Execute: 'Execute',
  Filter: 'Filter',
  Copied: 'Copied',
  'Asynchronous Rendering': 'Asynchronous Rendering',
  'Enable JavaScript Execution': 'Enable JavaScript Execution',
  'Catch Global Errors': 'Catch Global Errors',
  'Override Console': 'Override Console',
  'Auto Display If Error Occurs': 'Auto Display If Error Occurs',
  'Display Extra Information': 'Display Extra Information',
  'Display Unenumerable Properties': 'Display Unenumerable Properties',
  'Access Getter Value': 'Access Getter Value',
  'Lazy Evaluation': 'Lazy Evaluation',
  'Max Log Number': 'Max Log Number',
  infinite: 'infinite',

  // ---- Elements ----
  Empty: 'Empty',
  Attributes: 'Attributes',
  Styles: 'Styles',
  'Computed Style': 'Computed Style',
  'Event Listeners': 'Event Listeners',
  Refreshed: 'Refreshed',
  'Catch Event Listeners': 'Catch Event Listeners',

  // ---- Resources ----
  Script: 'Script',
  Stylesheet: 'Stylesheet',
  Iframe: 'Iframe',
  Image: 'Image',
  'Local Storage': 'Local Storage',
  'Session Storage': 'Session Storage',
  Key: 'Key',
  Value: 'Value',
  Cookie: 'Cookie',
  'Hide Eruda Setting': 'Hide Eruda Setting',
  'Auto Refresh Elements': 'Auto Refresh Elements',

  // ---- Sources ----
  'Show Line Numbers': 'Show Line Numbers',
  'Sorry, unable to fetch source code:(': 'Sorry, unable to fetch source code:(',

  // ---- Info ----
  Location: 'Location',
  'User Agent': 'User Agent',
  Device: 'Device',
  System: 'System',
  'Sponsor this Project': 'Sponsor this Project',
  About: 'About',
  screen: 'screen',
  viewport: 'viewport',
  'pixel ratio': 'pixel ratio',
  os: 'os',
  browser: 'browser',
  'Wechat Pay': 'Wechat Pay',

  // ---- Entry button ----
  'Remember Entry Button Position': 'Remember Entry Button Position',

  // ---- Shared data-grid columns & Network residues ----
  Name: 'Name',
  Method: 'Method',
  Status: 'Status',
  Type: 'Type',
  Size: 'Size',
  Time: 'Time',
  Total: 'Total',
  Header: 'Header',
  '(failed)': '(failed)',
  'Blocked by eruda': 'Blocked by eruda',
  'blocked (403)': 'blocked (403)',
  'unknown type': 'unknown type',
  'Request Data': 'Request Data',
  'Slow 3G': 'Slow 3G',
  'Fast 3G': 'Fast 3G',
  'No throttling': 'No throttling',
  Queueing: 'Queueing',
  'DNS Lookup': 'DNS Lookup',
  'Initial Connection': 'Initial Connection',
  'SSL/TLS': 'SSL/TLS',
  'Request Sent': 'Request Sent',
  'Waiting (TTFB)': 'Waiting (TTFB)',
  'Content Download': 'Content Download',
  more: 'more',

  // ---- Snippets ----
  'Enter the text': 'Enter the text',
  'Border All': 'Border All',
  'Add color borders to all elements': 'Add color borders to all elements',
  'Refresh Page': 'Refresh Page',
  'Add timestamp to url and refresh': 'Add timestamp to url and refresh',
  'Search Text': 'Search Text',
  'Highlight given text on page': 'Highlight given text on page',
  'Edit Page': 'Edit Page',
  'Toggle body contentEditable': 'Toggle body contentEditable',
  'Fit Screen': 'Fit Screen',
  'Scale down the whole page to fit screen': 'Scale down the whole page to fit screen',
  'Load Vue Plugin': 'Load Vue Plugin',
  'Vue devtools': 'Vue devtools',
  'Load Monitor Plugin': 'Load Monitor Plugin',
  'Display page fps, memory and dom nodes': 'Display page fps, memory and dom nodes',
  'Load Features Plugin': 'Load Features Plugin',
  'Browser feature detections': 'Browser feature detections',
  'Load Timing Plugin': 'Load Timing Plugin',
  'Show performance and resource timing': 'Show performance and resource timing',
  'Load Code Plugin': 'Load Code Plugin',
  'Edit and run JavaScript': 'Edit and run JavaScript',
  'Load Benchmark Plugin': 'Load Benchmark Plugin',
  'Run JavaScript benchmarks': 'Run JavaScript benchmarks',
  'Load Geolocation Plugin': 'Load Geolocation Plugin',
  'Test geolocation': 'Test geolocation',
  'Load Orientation Plugin': 'Load Orientation Plugin',
  'Test orientation api': 'Test orientation api',
  'Load Touches Plugin': 'Load Touches Plugin',
  'Visualize screen touches': 'Visualize screen touches',

  // ---- DevTools parity features ----
  'Live Expressions': 'Live Expressions',
  watchPh: 'e.g. window.innerWidth',
  addWatch: 'Add watch expression',
  'Watch': 'Watch',
  filterPh: 'Filter  (/regex/)',
  'Preserve Log': 'Preserve Log',
  restoredFromSession: 'Restored from the previous page session',
  'Search DOM': 'Search DOM',
  searchDomPh: 'Search by text or CSS selector',
  noMatches: 'No matches',
  'Copy selector': 'Copy selector',
  'Copy XPath': 'Copy XPath',
  // ---- DevTools-parity errors & settings ----
  'Uncaught': 'Uncaught',
  'Uncaught (in promise)': 'Uncaught (in promise)',
  'XHR finished loading': 'XHR finished loading',
  'Fetch finished loading': 'Fetch finished loading',
  'Fetch failed': 'Fetch failed',
  'Failed to load source': 'Failed to load source',
  'Log XMLHttpRequests': 'Log XMLHttpRequests',
  'Disable HTTP cache': 'Disable HTTP cache',
}

const zh = {
  // ---- Network tool ----
  record: '录制网络日志',
  stop: '停止录制网络日志',
  clear: '清除',
  exportHar: '导出 HAR',
  importHar: '导入 HAR',
  rules: '屏蔽 / 重写 / Mock',
  throttle: '网络节流',
  lang: 'EN',
  searchPh: '筛选 (/正则/  -排除)',
  all: '全部',
  xhr: 'Fetch/XHR',
  js: 'JS',
  css: 'CSS',
  img: '图片',
  media: '媒体',
  font: '字体',
  doc: '文档',
  other: '其他',
  requests: '个请求',
  transferred: '已传输',
  finish: '完成',
  failed: '失败',
  headers: '标头',
  cookies: 'Cookies',
  payload: '载荷',
  preview: '预览',
  response: '响应',
  initiator: '启动器',
  timing: '时间',
  stalled: '已停止',
  general: '常规',
  requestUrl: '请求网址',
  originalUrl: '原始网址（重写前）',
  requestMethod: '请求方法',
  statusCode: '状态代码',
  responseHeaders: '响应标头',
  requestHeaders: '请求标头',
  queryParams: '查询字符串参数',
  formData: '表单数据',
  requestPayload: '请求载荷',
  replay: '重放',
  copyCurl: '以 cURL 格式复制',
  copyFetch: '以 fetch 格式复制',
  copyResponse: '复制响应',
  blockedHint: '该请求已被屏蔽，未到达服务器，收到的是模拟的 HTTP 403 响应。',
  mockHint: '该响应由 Mock 规则生成，服务器并未被访问。',
  emptyBody: '该请求没有请求体。',
  emptyRes: '（空响应）',
  previewUnavailable: '该内容类型暂不支持预览。',
  timingHint: '该请求的阶段数据不可用（跨域且无 Timing-Allow-Origin），仅显示总耗时。',
  noStack: '未捕获到该请求的发起者信息。',
  initiatorHint: '捕获钩子之外的第一个脚本调用帧：',
  blocked: '屏蔽',
  rewrite: '重写',
  mock: 'Mock',
  manifestChip: '清单',
  wsChip: 'WS',
  wasmChip: 'Wasm',
  socketChip: 'Socket',
  manifest: '清单',
  ws: 'WS',
  wasm: 'Wasm',
  enableBlocking: '开启屏蔽',
  blockHint:
    '每行一条规则，支持字面子串或 /正则/，# 开头的行会被忽略。被屏蔽的请求不会到达服务器，并收到模拟的 403 响应。',
  save: '保存',
  enable: '启用',
  addRule: '添加规则',
  rewriteHint:
    '请求发出前，启用的规则会依次重写 URL：/正则/ 或字面子串将被替换为对应内容，自上而下生效。',
  mockHint2: '命中的请求不会访问网络，而是直接返回合成的响应。模式支持字面子串或 /正则/。',
  status: '状态',
  contentType: 'Content-Type',
  blockedStatus: '已屏蔽',
  blockedSaved: '黑名单已保存',
  rulesApplied: '规则已生效',
  copied: '已复制',
  replayed: '已重放',
  replayFailed: '重放失败：',
  harExported: 'HAR 已导出',
  harImported: 'HAR 已导入',
  harImportFailed: '无效的 HAR 文件',
  throttleOff: '已停用节流模式',
  offline: '离线',

  // ---- Network detail extras (aligned with Chrome DevTools zh-CN l10n) ----
  provisionalHeaders: '显示的是临时标头。',
  learnMore: '了解详情',
  noResponseData: '无法加载响应数据',
  currentlyRecording: '正在录制网络活动',
  recordingHint: '执行请求或刷新页面后，请求会显示在这里。',
  reloadPage: '刷新页面',
  duration: '耗时',
  explanation: '说明',
  resourceScheduling: '资源调度',
  connectionStart: '连接开始',
  requestResponse: '请求/响应',
  queuedAt: '排队于',
  startedAt: '开始于',
  totalDuration: '总耗时',
  serverTiming: '服务器计时',
  waitingServer: '等待服务器响应',

  // ---- Tool names ----
  Console: '控制台',
  Elements: '元素',
  Network: '网络',
  Resources: '资源',
  Sources: '来源',
  Info: '信息',
  Snippets: '代码段',
  Settings: '设置',

  // ---- DevTools / Settings ----
  Theme: '主题',
  'System preference': '跟随系统',
  Dark: '深色',
  Light: '浅色',
  Transparency: '透明度',
  'Display Size': '显示大小',
  'Restore defaults and reload': '恢复默认设置并刷新',
  'Language / 语言': '语言 / Language',
  'Follow System': '跟随系统',

  // ---- Console ----
  All: '全部',
  Warning: '警告',
  Error: '错误',
  Cancel: '取消',
  Execute: '执行',
  Filter: '过滤',
  Copied: '已复制',
  'Asynchronous Rendering': '异步渲染',
  'Enable JavaScript Execution': '启用 JavaScript 执行',
  'Catch Global Errors': '捕获全局错误',
  'Override Console': '覆写 Console 对象',
  'Auto Display If Error Occurs': '发生错误时自动打开',
  'Display Extra Information': '显示额外信息',
  'Display Unenumerable Properties': '显示不可枚举属性',
  'Access Getter Value': '读取 Getter 值',
  'Lazy Evaluation': '惰性求值',
  'Max Log Number': '最大日志条数',
  infinite: '无限',

  // ---- Elements ----
  Empty: '无',
  Attributes: '属性',
  Styles: '样式',
  'Computed Style': '计算样式',
  'Event Listeners': '事件监听器',
  Refreshed: '已刷新',
  'Catch Event Listeners': '捕获事件监听器',

  // ---- Resources ----
  Script: '脚本',
  Stylesheet: '样式表',
  Iframe: '框架',
  Image: '图片',
  'Local Storage': '本地存储',
  'Session Storage': '会话存储',
  Key: '键',
  Value: '值',
  Cookie: 'Cookie',
  'Hide Eruda Setting': '隐藏 Eruda 配置项',
  'Auto Refresh Elements': '自动刷新元素',

  // ---- Sources ----
  'Show Line Numbers': '显示行号',
  'Sorry, unable to fetch source code:(': '抱歉，无法获取源码 :(',

  // ---- Info ----
  Location: '位置',
  'User Agent': '用户代理 (UA)',
  Device: '设备',
  System: '系统',
  'Sponsor this Project': '赞助此项目',
  About: '关于',
  screen: '屏幕',
  viewport: '视口',
  'pixel ratio': '像素比',
  os: '操作系统',
  browser: '浏览器',
  'Wechat Pay': '微信支付',

  // ---- Entry button ----
  'Remember Entry Button Position': '记住入口按钮位置',

  // ---- Shared data-grid columns & Network residues ----
  Name: '名称',
  Method: '方法',
  Status: '状态',
  Type: '类型',
  Size: '大小',
  Time: '时间',
  Initiator: '启动器',
  Waterfall: '瀑布',
  Total: '总计',
  Header: '标头',
  'Request URL': '请求网址',
  'Request Method': '请求方法',
  'Status Code': '状态代码',
  '(failed)': '（失败）',
  'Blocked by eruda': '已被 eruda 屏蔽',
  'blocked (403)': '已屏蔽 (403)',
  'unknown type': '未知类型',
  'Request Data': '请求数据',
  'Slow 3G': '慢速 3G',
  'Fast 3G': '快速 3G',
  'No throttling': '已停用节流模式',
  Queueing: '正在排队',
  Stalled: '已停止',
  'DNS Lookup': 'DNS 查找',
  'Initial Connection': '初始连接',
  'SSL/TLS': 'SSL/TLS',
  'Request Sent': '已发送请求',
  'Waiting (TTFB)': '等待服务器响应 (TTFB)',
  'Content Download': '下载内容',
  more: '更多',

  // ---- Snippets ----
  'Enter the text': '输入要搜索的文本',
  'Border All': '元素边框',
  'Add color borders to all elements': '为页面所有元素添加彩色边框',
  'Refresh Page': '刷新页面',
  'Add timestamp to url and refresh': '在 URL 加上时间戳并刷新页面',
  'Search Text': '搜索文本',
  'Highlight given text on page': '在页面上高亮指定文本',
  'Edit Page': '编辑页面',
  'Toggle body contentEditable': '切换页面可编辑状态',
  'Fit Screen': '适配屏幕',
  'Scale down the whole page to fit screen': '缩放整个页面以适配屏幕',
  'Load Vue Plugin': '加载 Vue 插件',
  'Vue devtools': 'Vue 开发者工具',
  'Load Monitor Plugin': '加载监控插件',
  'Display page fps, memory and dom nodes': '显示页面 FPS、内存与 DOM 节点数',
  'Load Features Plugin': '加载特性检测插件',
  'Browser feature detections': '浏览器特性检测',
  'Load Timing Plugin': '加载 Timing 插件',
  'Show performance and resource timing': '显示性能与资源时序',
  'Load Code Plugin': '加载 Code 插件',
  'Edit and run JavaScript': '编辑并运行 JavaScript',
  'Load Benchmark Plugin': '加载性能测试插件',
  'Run JavaScript benchmarks': '运行 JavaScript 基准测试',
  'Load Geolocation Plugin': '加载地理定位插件',
  'Test geolocation': '测试地理定位 API',
  'Load Orientation Plugin': '加载方向传感器插件',
  'Test orientation api': '测试设备方向 API',
  'Load Touches Plugin': '加载触摸可视化插件',
  'Visualize screen touches': '可视化显示屏幕触摸轨迹',

  // ---- DevTools parity features ----
  'Live Expressions': '实时表达式',
  watchPh: '例如 window.innerWidth',
  addWatch: '添加监控表达式',
  'Watch': '监控',
  filterPh: '筛选  (/regex/)',
  'Preserve Log': '保留日志',
  restoredFromSession: '恢复自上次页面会话',
  'Search DOM': '搜索 DOM',
  searchDomPh: '按文本或 CSS 选择器搜索',
  noMatches: '无匹配项',
  'Copy selector': '复制选择器',
  'Copy XPath': '复制 XPath',
  // ---- DevTools 风格报错与设置 ----
  'Uncaught': '未捕获',
  'Uncaught (in promise)': '未捕获（promise 中）',
  'XHR finished loading': 'XHR 已完成加载',
  'Fetch finished loading': 'Fetch 已完成加载',
  'Fetch failed': 'Fetch 失败',
  'Failed to load source': '无法加载源代码',
  'Log XMLHttpRequests': '记录 XMLHttpRequest',
  'Disable HTTP cache': '禁用 HTTP 缓存',
}

const I18N = { en, zh }

export function detectLang() {
  try {
    const saved = localStorage.getItem(LANG_KEY)
    if (saved === 'zh' || saved === 'en') return saved
    // Migrate the legacy key used by the Network-only i18n.
    const legacy = localStorage.getItem(LEGACY_LANG_KEY)
    if (legacy === 'zh' || legacy === 'en') return legacy
  } catch {
    // Storage unavailable.
  }
  const nav = (
    navigator.language ||
    navigator.userLanguage ||
    'en'
  ).toLowerCase()
  return nav.indexOf('zh') === 0 ? 'zh' : 'en'
}

let lang = detectLang()

export function getLang() {
  return lang
}

export function setLang(l) {
  if (l !== 'zh' && l !== 'en') return
  if (l === lang) return
  lang = l
  try {
    localStorage.setItem(LANG_KEY, l)
    // Keep the legacy key in sync for older plugin builds.
    localStorage.setItem(LEGACY_LANG_KEY, l)
  } catch {
    // Storage unavailable.
  }
  emitter.emit(emitter.I18N, l)
}

export function t(key) {
  if (key == null) return key
  const dict = I18N[lang] || I18N.en
  let val = dict[key]
  if (val == null) val = I18N.en[key]
  return val == null ? key : val
}
